DevCycleHQ/ios-client-sdk

- README.md
Added docs for Carthage installation.
> chore: added docs for carthage installation

- DevCycle/DVCUser.swift
- DevCycle/ObjC/ObjCDVCUser.swift
- DevCycleTests/ObjC/ObjcDVCUserTests.m
- Examples/DevCycle-Example-App-ObjC/DevCycle-Example-App-ObjC/ViewController.m
- Examples/DevCycle-Example-App/DevCycle-Example-App/ViewController.swift
use CFBundleShortVersionString and CFBundleVersion to auto populate appVersion / appBuild
> DVC-2073 auto populate appVersion / appBuild

- DevCycle/DVCClient.swift
- DevCycle/Models/PlatformDetails.swift
- DevCycleTests/DVCUserTest.swift
- user may specify flush time in ms, default of 10s.
> fix: add automatic flushing of events

- DevCycle/Models/UserConfig.swift
- DevCycle/ObjC/ObjCUserConfig.swift
- DevCycleTests/Models/test_config.json
- Examples/DevCycle-Example-App/DevCycle-Example-App/ViewController.swift
- allows for easy identification of which variation of a given feature is being served to the user
> add variationName and variationKey to Feature model

- DevCycleTests/DVCVariableTests.swift
- DevCycleTests/EventQueueTests.swift
Added test for existing onUpdate functionality being called
> chore: added test for variable updating and calling onUpdate

- DevCycle/DVCClient.swift
- DevCycle/Models/Cache.swift
- DevCycle/Networking/DevCycleService.swift
- DevCycleTests/DevCycleServiceTests.swift
- Examples/DevCycle-Example-App/DevCycle-Example-App/ViewController.swift
Fixed saving anonymous user so resetting will make a new anonymous user every time.
> fix: removed caching anonymous user

- DevCycle/ObjC/ObjCDVCClient.swift
- Throw an error if user id is empty
> chore: throw error if user id is empty

- DevCycle/ObjC/ObjCDVCClient.swift
- Examples/DevCycle-Example-App-ObjC/DevCycle-Example-App-ObjC/ViewController.m
- fix objc code to pass in user id and is anonymous so the call doesn't fail
> fix: objc identify now passes in proper user info to get config

- DevCycle/DVCClient.swift
- DevCycleTests/Models/DVCClientTest.swift
* add `refetchConfig` method
* add unit test
> feat: add refetchConfig method

- DevCycle/DVCClient.swift
- DevCycleTests/Models/DVCClientTest.swift
- add an internal method to the builder and dvcclient to allow constructing a client with an injected service implementation
- update test file to use `setUp` for reusing the client builder and ensuring that the mock service is used
> correctly use mock test service when building client and reuse instantiation in tests

- DevCycle/DVCClient.swift
- DevCycle/SSEConnection.swift
- DevCycleTests/Models/DVCClientTest.swift
- add close method to flush any pending events and close streaming connection
- prevent new events from being tracked while closing
> add close method

- DevCycle/DVCClient.swift
- DevCycle/SSEConnection.swift
- DevCycleTests/Models/DVCClientTest.swift
Added notification observers to get notified when user has foregrounded / backgrounded to reconnect / disconnect the SSE connection
> feat: add foregrounded, backgrounded observers to reconnect/disconnect SSE

- DevCycle/DVCClient.swift
- DevCycle/DVCVariable.swift
- DevCycle/SSEConnection.swift
- DevCycleTests/Models/DVCClientTest.swift
- DevCycleTests/Models/DVCVariableTests.swift
- DevCycleTests/Models/UserConfigTests.swift
- DevCycleTests/Models/test_config.json
* client now stores variables in memory to be accessed later
* added unit tests
* fixed camel case in `test_config`
> feat: store created variables in memory

- DevCycle/Utils/UserPreferences.swift
- Examples/DevCycle-Example-App/Podfile.lock
- only setup to be caching anonymous user id right now
- get, set, and remove
> Setup UserPreferences wrapper class on UserDefaults

- DevCycle/DVCClient.swift
- DevCycle/Models/Cache.swift
- DevCycleTests/Networking/DevCycleServiceTests.swift
- read config from cache if `userId` matches and `fetchDate` is in range
> read config from cache on initialize

- scripts/deploy.sh
- includes pod push and sleuth deployment tracking
> chore: adds deploy script

- DevCycle/Models/UserConfig.swift
- add `evalReason` field to Feature struct
> [fix] add evalReason to Feature struct

- scripts/deploy.sh
see this issue for details on cocoapods issue: https://github.com/CocoaPods/CocoaPods/issues/11558#issuecomment-1284573492
> fix deploy.sh script building with watchOS simulators

- DevCycle/DVCClient.swift
- to prevent crashes on multiple threads
> [fix] add dispatch queue sync around variable calls

- .github/workflows/release.yml
contained the incorrect command to publish cocoapods
> fix: corrected cocoapods publish

- .github/workflows/ios.yaml
- .github/workflows/macos.yaml
- .github/workflows/tvos.yaml
- .github/workflows/watchos.yaml
Switching to https://github.com/marketplace/actions/setup-xcode-version
> fix: actions worker selecting xcode version

- .github/workflows/macos.yaml
- DevCycle.xcodeproj/project.pbxproj
- DevCycle/PrivacyInfo.xcprivacy
- Package.swift
- fastlane/Matchfile
> chore: add privacy manifest

- .github/workflows/check-semantic.yml
- .github/workflows/ios.yaml
- .github/workflows/macos.yaml
- .github/workflows/publish-pod.yml
- .github/workflows/release.yml
- .github/workflows/tvos.yaml
- .github/workflows/watchos.yaml
> chore: update build machine to macos-latest

- .github/workflows/check-semantic.yml
- .github/workflows/ios.yaml
- .github/workflows/macos.yaml
- .github/workflows/tvos.yaml
- .github/workflows/watchos.yaml
> chore: pin 3rd party actions to sha

- DevCycleTests/Models/DevCycleClientTests.swift
- added a test in client tests to check if a failed config will cause any errors when calling client methods if no config was fetched initially
> chore: added test for client to make sure if config request fails, that everything still works without a successful config

- DevCycle/DVCVariable.swift
- DevCycle/DevCycleClient.swift
- DevCycle/Models/DevCycleEvent.swift
- DevCycle/Models/EventQueue.swift
- DevCycle/Models/UserConfig.swift
- DevCycle/ObjC/ObjCDVCVariable.swift
- DevCycle/ObjC/ObjCDevCycleClient.swift
- DevCycle/ObjC/ObjCDevCycleEvent.swift
- DevCycle/ObjC/ObjCUserConfig.swift
- DevCycleTests/Models/DVCVariableTests.swift
- DevCycleTests/Models/DevCycleClientTests.swift
- DevCycleTests/Models/DevCycleEventTests.swift
- DevCycleTests/Models/UserConfigTests.swift
- DevCycleTests/Models/test_config_eval_reason.json
- DevCycleTests/ObjC/ObjCDevCycleClientTests.m
- feat: adds support for presenting eval reasons on Features & Variables
- this uses the new `EvalReason` class
- feat: reports eval reason as metadata for `variableEvaluated` events
- feat: adds default reasons for `Variable Type Mismatch` and `User Not Targeted`
- chore: updates tests and assertions to properly validate Eval Reason test data, including `target_id` field
- feat: add Eval handling to the Event Queue, update Event Queue tests
> feat: adds eval reasons
