- DevCycle-iOS.xcodeproj/project.pbxproj
- DevCycle/DVCClient.swift
- DevCycle/DVCUser.swift
- DevCycle/Models/CustomData.swift
- DevCycle/Networking/DevCycleService.swift
- DevCycle/ObjC/ObjCDVCClient.swift
- DevCycle/ObjC/ObjCDVCEvent.swift
- DevCycle/ObjC/ObjCDVCOptions.swift
- DevCycle/ObjC/ObjCDVCUser.swift
- DevCycle/ObjC/ObjCDVCVariable.swift
- DevCycle/ObjC/ObjCUserConfig.swift
- DevCycleTests/ObjC/ObjCDVCClientTests.m
- DevCycleTests/ObjC/ObjcDVCUserTests.m
- DevCycleTests/ObjC/ObjcDVCVariableTests.m
- Examples/DevCycle-Example-App-ObjC/DevCycle-Example-App-ObjC/AppDelegate.m
- Examples/DevCycle-Example-App-ObjC/DevCycle-Example-App-ObjC/Managers/DevCycleManager.h
- Examples/DevCycle-Example-App-ObjC/DevCycle-Example-App-ObjC/Managers/DevCycleManager.m
- Examples/DevCycle-Example-App-ObjC/DevCycle-Example-App-ObjC/ViewController.m
Made changes to the builder pattern where all the builder values are evaluated by the `initialize:` method not before being passed into the `initialize:` method. This allows for only one `err` response that needs to be checked. Kept the existing interface in-place for now, we can clean this all up a bunch once we decide on which way to go.
> DVC-1955 Update Obj-C SDK interface

- DevCycle-iOS.xcodeproj/project.pbxproj
- DevCycle/DVCClient.swift
- DevCycle/Models/DVCEvent.swift
- DevCycle/Models/EventQueue.swift
- DevCycleTests/DVCClientTest.swift
- DevCycleTests/EventQueueTests.swift
- Examples/DevCycle-Example-App/DevCycle-Example-App.xcodeproj/project.pbxproj
- Examples/DevCycle-Example-App/DevCycle-Example-App/ViewController.swift
- fastlane/Fastfile
- user can now use a callback when calling `flushEvents`
- when a flush is finished, if the queue is not empty again it will schedule a flush (an error with the flush will cause it to re-add to the queue, which will then trigger a scheduled flush)
- removed timer that persisted indefinitely
> feat: Flush Callback

- DevCycle/Networking/DevCycleService.swift
- tracked events are converted only prior to being sent to DevCycle
> fix to update Event payload to properly track customEvents

- DevCycle/DVCUser.swift
- DevCycleTests/DVCUserTest.swift
- when creating user, setting `isAnonymous` to `false` and passing in no `user_id` still made an anonymous `user_id`, now it fails to create one
> fix: setting is anonymous to false and passing in no user_id now doesn't create dvcuser

- DevCycle/DVCClient.swift
- DevCycle/Models/DVCOptions.swift
- DevCycle/Models/UserConfig.swift
- DevCycle/Networking/DevCycleService.swift
- DevCycle/ObjC/ObjCDVCOptions.swift
- DevCycleTests/DVCClientTest.swift
- DevCycleTests/DVCOptionsTest.swift
- DevCycleTests/DevCycleServiceTests.swift
- DevCycleTests/EventQueueTests.swift
- follows similar logic to js sdk
- calls `saveEntity` on initialize
- add tests and fix existing tests
> feat: enable edge DB on iOS

- DevCycle/DVCClient.swift
After identification or reset save user to local memory to associate events with proper user.
> fix: events now get associated with updated identified / reset user

- DevCycle/DVCClient.swift
- DevCycle/Networking/DevCycleService.swift
Posting events is possible now with an empty feature variation map.
> fix: posting events can now do so with empty feature variation map

- DevCycle/Models/EventQueue.swift
- DevCycleTests/EventQueueTests.swift
Check error code to see if we can retry to queue the failed events.
> feat: only retry failed events if error code is >= 500

- DevCycle/DVCClient.swift
- DevCycleTests/DVCClientTest.swift
For `variable` calls, return early and log an error if the key has any unsupported characters: i.e. not in `a-z0-9(-)(_)`
> chore: return default for unsupported keys for dvc variable calls

- DevCycle-iOS.xcodeproj/project.pbxproj
- DevCycle/DVCClient.swift
- DevCycle/DVCVariable.swift
- DevCycle/Models/DVCConfig.swift
- DevCycle/Utils/NotificationNames.swift
- DevCycleTests/Models/DVCClientTest.swift
When config gets set, post a notification for any observers watching for new config. This will update the variable value for any variable, as it adds an observer on init.
> chore: post notifications for variables to call onUpdate handler 

- DevCycle-iOS.xcodeproj/project.pbxproj
- DevCycle/DVCClient.swift
- DevCycle/Models/UserConfig.swift
- DevCycle/Networking/DevCycleService.swift
- DevCycle/SSEConnection.swift
- DevCycleTests/Models/DVCClientTest.swift
- DevCycleTests/Models/EventQueueTests.swift
- DevCycleTests/Models/SSEMessage.swift
- DevCycleTests/Utils/RequestConsolidatorTests.swift
* refetch config when an sse message is received
* send `sse` and `sseLastModified` query params in config request
* add unit test for initializing an `SSEMessage` object
> feat: refetch config when sse message is received

- DevCycle/DVCClient.swift
- always clear cached anon user id on reset
- fix clearing cached anon user id on successful identify calls, if user is *not* anonymous
- keep the anon user id in cache if identifying with `isAnonymous` true
> clear anon user id on reset and fix clearing on successful identify calls

- DevCycle/DVCClient.swift
- DevCycle/DVCUser.swift
- DevCycleTests/Models/DVCUserTest.swift
- if no `userId` is passed in, implied anonymous
- fix restoring cached id if `resetUser` fails
- update tests
> Initialize users as anonymous implicitly

- DevCycle/DVCClient.swift
- `resetUser` still separately handles clearing anon user Id, and restoring it when config fetch fails
> clear anon user id when client initialized with non-anon user

- DevCycle/DVCClient.swift
- DevCycle/Models/DVCOptions.swift
- DevCycleTests/Models/DVCOptionsTest.swift
- `isConfigCached` defaults to false
- `disableConfigCache` defaults to false
- `configCacheTTL` defaults to 7 days = 604800000 ms
> add initialization options and isConfigCached to DVCClient

- DevCycle/DVCClient.swift
Previously whenever a non-anonymous user was idenified we would clear the cached anon ID. Instead we will only overwrite it when a new anon ID is generated (ie. via reset)
> Don't clear anonymous user ID when identifying a user

- DevCycle/Utils/RequestConsolidator.swift
- set the `requestInFlight` flag to false before the callback, as we've already processed the config at this point
> fix config fetch in callback by setting requestInFlight flag

- DevCycle/Models/DVCEvent.swift
- DevCycle/ObjC/ObjCDVCEvent.swift
- DevCycleTests/Models/DVCClientTest.swift
- change `DVCEvent.value` from `Int` to `Double`
> [fix] convert DVCEvent value attribute to Double instead of Int

- DevCycle/Networking/DevCycleService.swift
Properly encode `+` in query params because Apple doesn't want to.
> fix: percent encode + properly in query param

- DevCycle/Models/PlatformDetails.swift
ref: https://stackoverflow.com/questions/20070333/obtain-model-identifier-string-on-os-x
testing using the output here :
```
[DevCycle][debug][request] Request completed: https://sdk-api.devcycle.com/v1/mobileSDKConfig?user_id=CAED436D-A83A-471A-8E61-2EBBD661B626&isAnonymous=true&appVersion=1.0&appBuild=1&lastSeenDate=1673925186&createdDate=1673925186&platform=macos&platformVersion=Version%2013.0.1%20(Build%2022A400)&deviceModel=MacBookPro18,1&sdkType=mobile&sdkVersion=1.7.2&enableEdgeDB=false&envKey=dvc_mobile_6da261ea_09f4_4674_8383_82e48334a5e4_2f64c74, response time: 317.23594665527344 ms
```
> [feat] add model identifier for osx

- DevCycle/DVCClient.swift
Reverts DevCycleHQ/ios-client-sdk#149 which removed the deadlock introduced
> Revert "[fix] add dispatch queue sync around variable calls"

- DevCycle.xcodeproj/project.pbxproj
- DevCycle/DVCClient.swift
- DevCycleTests/Models/ThreadingTests.swift
Added a separate queue to prevent crashes from accessing `variableInstanceDictionary` in separate threads.
> fix: fix variable getting called from multiple threads causing a crash

- DevCycle.podspec
Config needs to use versions prefixed with "v" to release
> fix: update cocoapods release to use v-based version

- DevCycle/DevCycleClient.swift
- DevCycle/Models/DevCycleOptions.swift
- DevCycle/ObjC/ObjCDevCycleOptions.swift
- DevCycleTests/Models/DevCycleOptionsTest.swift
- Rename `DevCycleOptions.flushEventsIntervalMs` to `eventFlushIntervalMS` to be consistent with other client SDKs. Mark `flushEventsIntervalMs` as deprecated.
> feat: rename DevCycleOptions.flushEventsIntervalMs to eventFlushIntervalMS

- DevCycle/DevCycleUser.swift
difference between internal and public: https://medium.com/hash-coding/swift-access-control-ios-dab45a0b79ab#:~:text=Public%20%E2%80%94%20This%20is%20the%20same,outside%20the%20module(target).
> fix: switch DevCycleUser platform params to internal from public

- DevCycle/DVCVariable.swift
- DevCycle/DevCycleClient.swift
- DevCycle/Models/UserConfig.swift
- DevCycle/ObjC/ObjCDVCVariable.swift
- DevCycle/ObjC/ObjCDevCycleClient.swift
- DevCycle/ObjC/ObjCUserConfig.swift
- DevCycleTests/Models/DVCVariableTests.swift
- DevCycleTests/Models/DevCycleClientTests.swift
- DevCycleTests/Models/UserConfigTests.swift
- DevCycleTests/ObjC/ObjCDevCycleClientTests.m
- DevCycleTests/ObjC/ObjcDVCVariableTests.m
To resolve issues where the generic type of a `DVCVariable` could be different depending on if the default value or bucketed value was used, these changes were needed: 
- locking down the iOS SDK Swift interface for `variable()` and `variableValue()` to only support known supported types: `String` \ `Boolean` \ `Double` \ `NSNumber` \ `Dictionary` \ `NSDictionary`.
- added `DVCVariableTypes` enum to explicitly mark the variable type.
- Updated tests to support these changes
> feat: update variable interface to known supported types

- .github/workflows/ios.yaml
- .github/workflows/publish-pod.yml
- .github/workflows/release.yml
- scripts/deploy.sh
- update deploy script to remove unused sleuth call
- adds new publish-pod workflow that triggers on Tag pushes on main to publish the DevCycle pod to CocoaPod
- remove publish-cocoapods step from release workflow
> chore: update release workflows to trigger CocoaPod Publish workflow on new tag push

- DevCycle/DevCycleClient.swift
- DevCycleTests/Models/DevCycleClientTests.swift
This reverts a change that caused issues with the last release, where we removed the generic interfaces to `variable()` and `variableValue()`. These interfaces should have been left in the SDKs as deprecated methods to avoid breaking backward compatibility.
> fix: re-add deprecated generic variable() and variableValue() methods

- DevCycle/Models/DevCycleOptions.swift
- DevCycle/Networking/DevCycleService.swift
- DevCycleTests/Models/DevCycleOptionsTest.swift
- DevCycleTests/Networking/DevCycleServiceTests.swift
- added eventsApiProxyURL option separate from apiProxyURL
- added tests
> chore: added eventsApiProxyURL option for proxying to a different url than the sdk config

- .github/workflows/ios.yaml
- .github/workflows/macos.yaml
- .github/workflows/tvos.yaml
- .github/workflows/watchos.yaml
- DevCycle/Networking/DevCycleService.swift
- DevCycleTests/Models/DevCycleClientTests.swift
- DevCycleTests/Models/EventQueueTests.swift
- DevCycleTests/Networking/DevCycleServiceTests.swift
- send events payload in batches of 100 events to reduce errors
- switches the GH Actions image to `macos-13-large`
> fix: batch event payloads into chunks of 100 to reduce errors on event processing

- DevCycle/Networking/DevCycleService.swift
- DevCycleTests/Networking/DevCycleServiceTests.swift
- reverts event batching, events will be flushed in a single request every flush interval
> fix: revert event batching

- DevCycle/DevCycleClient.swift
- added observer for when app becomes active to cover case when control center is dismissed so that we can reconnect the streaming connection for SSE
> fix: fixed streaming connection not connecting when control center is dismissed

- .github/workflows/macos.yaml
Potential fix for [https://github.com/DevCycleHQ/ios-client-sdk/security/code-scanning/2](https://github.com/DevCycleHQ/ios-client-sdk/security/code-scanning/2)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will specify the minimal permissions required for the workflow to function correctly. Based on the provided code, the workflow primarily interacts with repository contents and uses a GitHub token for authentication. Therefore, we will set `contents: read` as the minimal permission. If additional permissions are required in the future, they can be added explicitly.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> chore: Potential fix for code scanning alert no. 2: Workflow does not contain permissions

- .github/workflows/ios.yaml
Potential fix for [https://github.com/DevCycleHQ/ios-client-sdk/security/code-scanning/1](https://github.com/DevCycleHQ/ios-client-sdk/security/code-scanning/1)
To fix the issue, add a `permissions` block at the root of the workflow file to explicitly define the minimal permissions required. Based on the workflow steps, the workflow primarily reads repository contents and does not perform any write operations. Therefore, the `contents: read` permission is sufficient. This change ensures that the workflow adheres to the principle of least privilege.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> chore: Potential fix for code scanning alert no. 1: Workflow does not contain permissions

- .github/workflows/watchos.yaml
Potential fix for [https://github.com/DevCycleHQ/ios-client-sdk/security/code-scanning/4](https://github.com/DevCycleHQ/ios-client-sdk/security/code-scanning/4)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will specify the minimal permissions required for the workflow to function correctly. Based on the actions used in the workflow, the following permissions are likely sufficient:
- `contents: read` for accessing the repository's contents.
- `packages: read` for accessing any required packages.
- `pull-requests: write` if the workflow interacts with pull requests (e.g., adding comments or labels).
If the workflow does not require any write permissions, we will limit it to `contents: read` only.
---
_Suggested fixes powered by Copilot …
> chore: Potential fix for code scanning alert no. 4: Workflow does not contain permissions

- DevCycle/DVCVariable.swift
- Updating DVCVariable `init` functions to be public so I can use them in tests for the `DevCycleOpenFeatureProvider` in its repo.
> fix: making DVCVariable init functions public to properly test OF Provider

- .github/workflows/release.yml
This PR updates the release workflow to explicitly create and push a version tag (prefixed with `v`) before creating the GitHub release. This ensures that tag-based workflows (like CocoaPods publishing) are triggered reliably, since tags created via the GitHub API do not fire the `push` event.
> fix: create and push the tag to properly trigger the cococapods publish action

- DevCycle/DevCycleClient.swift
- DevCycle/DevCycleUser.swift
- DevCycle/Models/Cache.swift
- DevCycleTests/Mocks/URLSessionMock.swift
- DevCycleTests/Models/DVCVariableTests.swift
- DevCycleTests/Models/DevCycleClientTests.swift
- DevCycleTests/Models/DevCycleUserTest.swift
- DevCycleTests/Models/EventQueueTests.swift
- DevCycleTests/Models/SSEMessage.swift
- DevCycleTests/Models/ThreadingTests.swift
- DevCycleTests/Models/UserConfigTests.swift
- DevCycleTests/Networking/DevCycleServiceTests.swift
- Examples/DevCycle-MacOS-Example-App/DevCycle-macOS-Example-App.xcodeproj/project.pbxproj
- Examples/DevCycle-MacOS-Example-App/DevCycle-macOS-Example-App/AppDelegate.swift
- Examples/DevCycle-MacOS-Example-App/DevCycle-macOS-Example-App/DevCycleManager.swift
- Examples/DevCycle-MacOS-Example-App/DevCycle-macOS-Example-App/ViewController.swift
- Examples/DevCycle-MacOS-Example-App/Podfile
- Examples/DevCycle-iOS-Example-App-Swift/DevCycle-iOS-Example-App-Swift/AppDelegate.swift
- Examples/DevCycle-iOS-Example-App-Swift/DevCycle-iOS-Example-App-Swift/DevCycleManager.swift
- Examples/DevCycle-iOS-Example-App-Swift/DevCycle-iOS-Example-App-Swift/ViewController.swift
- Examples/DevCycle-tvOS-Example-App/DevCycle-tvOS-Example-App/AppDelegate.swift
- Examples/DevCycle-tvOS-Example-App/DevCycle-tvOS-Example-App/DevCycleManager.swift
- Examples/DevCycle-tvOS-Example-App/DevCycle-tvOS-Example-App/ViewController.swift
- Gemfile
- Gemfile.lock
Added comments where the main changes are as a lot of these changes are just auto formatting changes.
- Added async methods to all public methods in DevCycleUser
- Updated tests to test new async methods and fix some test issues.
- Updated anon user id caching logic
> feat: add async versions of all public DevCycleClient methods with callbacks

- .github/workflows/ios.yaml
- .github/workflows/macos.yaml
- .github/workflows/tvos.yaml
- .github/workflows/watchos.yaml
- DevCycle/DevCycleUser.swift
- DevCycleTests/Models/DevCycleUserTest.swift
🐛 Fix UserBuilder validation logic
- Fixed validation: Now throws UserError.MissingUserIdAndIsAnonymousFalse when isAnonymous=false but no valid userId provided
- Simplified logic: Removed premature side effects from userId() and isAnonymous() methods
- Better empty handling: Whitespace-only userIds are trimmed and treated as empty
- Added tests: Comprehensive coverage for all user creation scenarios
⚠️ Breaking: builder().isAnonymous(false).build() now throws an error instead of silently creating anonymous user
> fix: improve UserBuilder validation and add error for isAnonymous=false with no userId

- .github/workflows/publish-pod.yml
> fix: try and fix publish-pod permissions

- .gitignore
- DevCycle.xcodeproj/project.pbxproj
- DevCycle/DevCycleClient.swift
- DevCycle/Models/DevCycleEvent.swift
- DevCycle/Models/UserConfig.swift
- DevCycle/Networking/DevCycleService.swift
- DevCycle/ObjC/ObjCDevCycleEvent.swift
- DevCycle/SSEConnection.swift
- DevCycle/Utils/ProcessConfig.swift
- DevCycle/Utils/RequestConsolidator.swift
- DevCycleTests/Models/DevCycleEventTests.swift
- DevCycleTests/Networking/DevCycleServiceTests.swift
- replaced all instances of unsafe casting `as!` 
- added test file for DevCycleEvent
> fix: remove unsafe casts to prevent runtime exceptions

- DevCycle/DevCycleClient.swift
- DevCycleTests/Models/DevCycleClientTests.swift
- fix: use a cached config (if available), if identify user request fails
> fix: use cached config if identify user fails 

- DevCycle/DevCycleClient.swift
- DevCycle/Models/Cache.swift
- DevCycleTests/Models/DevCycleClientTests.swift
- DevCycleTests/Networking/DevCycleServiceTests.swift
- DevCycleTests/Utils/RequestConsolidatorTests.swift
- fix: logs a warning & deletes the invalid cached config if there is an error parsing the cached config into a valid UserConfig (due to that current SDK version requiring different properties from the current cached config)
- chore: increases some test timeouts to prevent flaking on CI
> fix: gracefully handle errors when parsing a cached config
